持续演进 2023-09-01

diff --git a/vendor/github.com/gosnmp/gosnmp/Makefile b/vendor/github.com/gosnmp/gosnmp/Makefile
--- a/vendor/github.com/gosnmp/gosnmp/Makefile
+++ b/vendor/github.com/gosnmp/gosnmp/Makefile
@@ -1,13 +1,25 @@
 .PHONY: test lint lint-all lint-examples tools
 
-GOLANGCI_LINT_VERSION ?= v1.45.2
+GOLANGCI_LINT_VERSION ?= v1.54.2
 
 test:
 	go test *.go
 
-lint:
+lint: check_license
 	golangci-lint run -v
 
 tools:
 	curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/$(GOLANGCI_LINT_VERSION)/install.sh \
 		| sh -s -- -b $(GOPATH)/bin $(GOLANGCI_LINT_VERSION)
+
+.PHONY: check_license
+check_license:
+	@echo ">> checking license header"
+	@licRes=$$(for file in $$(find . -type f -iname '*.go' ! -path './vendor/*') ; do \
+               awk 'NR<=3' $$file | grep -Eq "(Copyright [0-9]+ The GoSNMP Authors|generated|GENERATED)" || echo $$file; \
+       done); \
+       if [ -n "$${licRes}" ]; then \
+               echo "license header checking failed:"; echo "$${licRes}"; \
+               exit 1; \
+       fi
+
